package com.riczz.meterreader.enums;

public enum ImageType {
    IMAGE_RESIZED,
    IMAGE_MORPHED,
    IMAGE_BLURRED,
    IMAGE_BGMAX,
    IMAGE_SUBTRACTED,
    IMAGE_TRESHOLDED,
    IMAGE_DILATED,
    IMAGE_CANNY,
    IMAGE_CONTOURED,

    IMAGE_MODIFIED,
    IMAGE_WARPED,
    MASK_DIALS,
    IMAGE_CORRECTED,

    DIAL_SEARCH_MASK,
    DIAL_SEARCH_CANNY,
    DIAL_SEARCH_CROPPED,

    SKEWNESS_THRESHOLDED,
    SKEWNESS_MORPH_OPEN,
    SKEWNESS_MORPH_CLOSE,
    SKEWNESS_CANNY,
    SKEWNESS_LINES,

    CORRECTION_MEDIAN,
    CORRECTION_B_C,
    CORRECTION_GAMMA,
    CORRECTION_RESULT,

    DIGITDETECT_DENOISED,

}
